name: Deploy to multiple environments
on:
  push:
    branches: [ "master" ]
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
      
    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo deploiment vers dev


  deploy-rec:
    runs-on: ubuntu-latest
    environment:
      name: rec
    needs: [deploy-dev]

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo deploiment vers rec               
