name: Deploy to multiple environments
on:
  push:
    branches: [ "master" ]
jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: deploiment vers dev


  deploy-rec:
    runs-on: ubuntu-latest
    environment:
      name: rec
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: deploiment vers rec               
